from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from datetime import datetime
import os

class PDFReportGenerator:
    """Professional PDF Report Generator - Dynamic"""
    
    def __init__(self, output_file='report.pdf'):
        self.output_file = output_file
        self.doc = SimpleDocTemplate(output_file, pagesize=A4,
                                     rightMargin=0.5*inch, leftMargin=0.5*inch,
                                     topMargin=0.75*inch, bottomMargin=0.75*inch)
        self.story = []
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=28,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=6,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold',
            borderColor=colors.HexColor('#3498db'),
            borderWidth=2,
            borderPadding=8
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['BodyText'],
            fontSize=11,
            alignment=TA_JUSTIFY,
            spaceAfter=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='Subtitle',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.HexColor('#7f8c8d'),
            alignment=TA_CENTER,
            spaceAfter=20
        ))
    
    def add_title_page(self, title, subtitle, date_str):
        """Add professional title page with Insightify branding"""
        # Top branding
        self.story.append(Spacer(1, 0.5*inch))
        branding = Paragraph(
            "<font size=14><b>📊 INSIGHTIFY</b></font><br/><font size=9>Professional Data Analysis & Report Generation</font>",
            ParagraphStyle(
                'Branding',
                parent=self.styles['Normal'],
                fontSize=14,
                textColor=colors.HexColor('#3498db'),
                alignment=TA_CENTER,
                spaceAfter=20
            )
        )
        self.story.append(branding)
        
        # Decorative line
        self.story.append(Spacer(1, 0.3*inch))
        
        # Title
        self.story.append(Spacer(1, 1*inch))
        title_para = Paragraph(title, self.styles['CustomTitle'])
        self.story.append(title_para)
        
        # Subtitle
        self.story.append(Spacer(1, 0.3*inch))
        subtitle_para = Paragraph(subtitle, self.styles['Subtitle'])
        self.story.append(subtitle_para)
        
        # Date and metadata
        self.story.append(Spacer(1, 1*inch))
        metadata_text = f"""
        <b>Report Generated:</b> {date_str}<br/>
        <b>Platform:</b> Insightify Professional Analytics<br/>
        <b>Version:</b> 2.0 (Dynamic Engine)<br/>
        <b>Status:</b> Confidential
        """
        metadata_para = Paragraph(metadata_text, self.styles['Normal'])
        self.story.append(metadata_para)
        
        # Footer branding
        self.story.append(Spacer(1, 1.5*inch))
        footer_branding = Paragraph(
            "<i>Generated by Insightify - Professional Data Analysis Platform<br/>www.insightify.com</i>",
            ParagraphStyle(
                'FooterBranding',
                parent=self.styles['Normal'],
                fontSize=9,
                textColor=colors.HexColor('#7f8c8d'),
                alignment=TA_CENTER
            )
        )
        self.story.append(footer_branding)
        
        self.story.append(PageBreak())
    
    def add_executive_summary(self, analysis_results):
        """Add executive summary section"""
        self.story.append(Paragraph("Executive Summary", self.styles['CustomHeading']))
        
        basic_stats = analysis_results.get('basic_stats', {})
        
        summary_text = f"""
        <b>Report Overview:</b><br/>
        This comprehensive data analysis report presents key insights and metrics from the provided dataset.
        The analysis covers {basic_stats.get('total_records', 0):,} records with {basic_stats.get('total_columns', 0)} columns.<br/><br/>
        
        <b>Dataset Composition:</b><br/>
        • Numeric Columns: <b>{basic_stats.get('numeric_columns', 0)}</b><br/>
        • Categorical Columns: <b>{basic_stats.get('categorical_columns', 0)}</b><br/>
        • Date Columns: <b>{basic_stats.get('date_columns', 0)}</b><br/>
        • Missing Values: <b>{basic_stats.get('missing_values', 0)}</b><br/>
        • Duplicate Rows: <b>{basic_stats.get('duplicate_rows', 0)}</b>
        """
        
        self.story.append(Paragraph(summary_text, self.styles['CustomBody']))
        self.story.append(Spacer(1, 0.3*inch))
    
    def add_numeric_analysis(self, analysis_results):
        """Add numeric analysis section"""
        if 'numeric_analysis' not in analysis_results:
            return
            
        self.story.append(Paragraph("Numeric Analysis", self.styles['CustomHeading']))
        
        numeric_data = analysis_results['numeric_analysis']
        
        # Create a summary table for numeric columns
        table_data = [['Column', 'Mean', 'Median', 'Min', 'Max']]
        
        for col, stats in numeric_data.items():
            row = [
                col[:20], # Truncate long names
                f"{stats['mean']:.2f}",
                f"{stats['median']:.2f}",
                f"{stats['min']:.2f}",
                f"{stats['max']:.2f}"
            ]
            table_data.append(row)
            
        # Limit table size if too many columns
        if len(table_data) > 20:
            table_data = table_data[:20]
            self.story.append(Paragraph("<i>(Showing top 20 numeric columns)</i>", self.styles['Normal']))

        t = Table(table_data, colWidths=[2*inch, 1.2*inch, 1.2*inch, 1.2*inch, 1.2*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3498db')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#ecf0f1')])
        ]))
        self.story.append(t)
        self.story.append(PageBreak())

    def add_categorical_analysis(self, analysis_results):
        """Add categorical analysis section"""
        if 'categorical_analysis' not in analysis_results:
            return

        self.story.append(Paragraph("Categorical Analysis", self.styles['CustomHeading']))
        
        cat_data = analysis_results['categorical_analysis']
        
        for col, stats in list(cat_data.items())[:5]: # Show details for top 5 categorical cols
            self.story.append(Paragraph(f"<b>Column: {col}</b>", self.styles['Normal']))
            self.story.append(Paragraph(f"Unique Values: {stats['unique_count']}", self.styles['Normal']))
            self.story.append(Paragraph(f"Most Frequent: {stats['most_frequent']}", self.styles['Normal']))
            
            # Top values table
            top_vals = [['Value', 'Count']]
            for val, count in stats['top_values'].items():
                top_vals.append([str(val)[:30], str(count)])
            
            t = Table(top_vals, colWidths=[4*inch, 2*inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#9b59b6')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ]))
            self.story.append(t)
            self.story.append(Spacer(1, 0.2*inch))
            
        self.story.append(PageBreak())

    def add_correlations(self, analysis_results):
        """Add correlation analysis"""
        if 'correlations' not in analysis_results:
            return

        self.story.append(Paragraph("Correlation Analysis", self.styles['CustomHeading']))
        self.story.append(Paragraph("Significant correlations found between variables:", self.styles['Normal']))
        
        corrs = analysis_results['correlations']
        if not corrs:
            self.story.append(Paragraph("No significant correlations found.", self.styles['Normal']))
            return

        table_data = [['Variables Pair', 'Correlation Coefficient']]
        for corr in corrs[:10]: # Top 10
            table_data.append([corr['pair'], f"{corr['value']:.4f}"])
            
        t = Table(table_data, colWidths=[4*inch, 2*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e74c3c')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        self.story.append(t)
        self.story.append(PageBreak())

    def add_visualizations(self, chart_dir):
        """Add visualization charts to report"""
        self.story.append(Paragraph("Data Visualizations", self.styles['CustomHeading']))
        
        if not os.path.exists(chart_dir):
            return

        chart_files = sorted([f for f in os.listdir(chart_dir) if f.endswith('.png')])
        
        for i, chart_file in enumerate(chart_files):
            chart_path = os.path.join(chart_dir, chart_file)
            
            # Add chart title
            chart_title = chart_file.replace('_', ' ').replace('.png', '').replace('0', '', 1).strip()
            # Remove sorting prefix if present (e.g., "01_")
            if chart_title[0].isdigit() and chart_title[1].isdigit():
                 chart_title = chart_title[2:].strip()

            self.story.append(Paragraph(f"<b>{chart_title.title()}</b>", self.styles['Normal']))
            
            # Add image
            try:
                img = Image(chart_path, width=6.5*inch, height=4*inch)
                self.story.append(img)
                self.story.append(Spacer(1, 0.2*inch))
                
                # Add page break after every 2 charts
                if (i + 1) % 2 == 0 and i < len(chart_files) - 1:
                    self.story.append(PageBreak())
            except Exception as e:
                print(f"Error adding image {chart_file}: {e}")
        
        self.story.append(PageBreak())
    
    def add_conclusions(self):
        """Add conclusions section"""
        self.story.append(Paragraph("Conclusions & Recommendations", self.styles['CustomHeading']))
        
        conclusions_text = """
        <b>Automated Insights:</b><br/>
        1. <b>Data Quality:</b> The dataset has been analyzed for completeness and integrity. 
        Please review the Executive Summary for details on missing values or duplicates.<br/><br/>
        
        2. <b>Statistical Trends:</b> The Numeric Analysis section highlights the central tendencies and spread of your data.
        Outliers or extreme values can be identified from the Min/Max values.<br/><br/>
        
        3. <b>Relationships:</b> The Correlation Analysis (if applicable) has identified potential relationships between variables.
        Strong correlations (close to 1 or -1) suggest predictive power.<br/><br/>
        
        <b>Recommendations:</b><br/>
        • Investigate any high correlation pairs to understand causal relationships.<br/>
        • Review categorical distributions to identify dominant groups or rare classes.<br/>
        • Use the generated visualizations to present findings to stakeholders.<br/>
        """
        
        self.story.append(Paragraph(conclusions_text, self.styles['CustomBody']))
        self.story.append(Spacer(1, 0.5*inch))
        
        # Footer
        footer_text = f"""
        <i>Report Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br/>
        This report contains confidential business information and should be handled accordingly.</i>
        """
        self.story.append(Paragraph(footer_text, self.styles['Normal']))
    
    def build(self):
        """Build and save the PDF"""
        try:
            self.doc.build(self.story)
            print(f"[✓] PDF Report generated: {self.output_file}")
        except Exception as e:
            print(f"[✗] Error building PDF: {e}")
            import traceback
            traceback.print_exc()
